before_script:
  - echo "tag => '$CI_COMMIT_TAG'"
  - $VERSION=$CI_COMMIT_TAG
  - echo "version => '$VERSION'"

stages:
  - build

build:
  stage: build
  tags:
    - win10_builder
  only:
    - /(^v\d+\.\d+\.\d+$)|(^build$)/
  except:
    - branches
  script:
    - wails build