// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddConnection(arg1, arg2, arg3, arg4) {
  return window['go']['controller']['App']['AddConnection'](arg1, arg2, arg3, arg4);
}

export function CreateBucket(arg1, arg2) {
  return window['go']['controller']['App']['CreateBucket'](arg1, arg2);
}

export function DelConnection(arg1) {
  return window['go']['controller']['App']['DelConnection'](arg1);
}

export function DeleteBucket(arg1, arg2) {
  return window['go']['controller']['App']['DeleteBucket'](arg1, arg2);
}

export function DeleteObject(arg1, arg2, arg3) {
  return window['go']['controller']['App']['DeleteObject'](arg1, arg2, arg3);
}

export function DoConnect(arg1) {
  return window['go']['controller']['App']['DoConnect'](arg1);
}

export function GetObject(arg1, arg2, arg3) {
  return window['go']['controller']['App']['GetObject'](arg1, arg2, arg3);
}

export function HeadObject(arg1, arg2, arg3) {
  return window['go']['controller']['App']['HeadObject'](arg1, arg2, arg3);
}

export function ListBucket(arg1) {
  return window['go']['controller']['App']['ListBucket'](arg1);
}

export function ListConnection(arg1, arg2) {
  return window['go']['controller']['App']['ListConnection'](arg1, arg2);
}

export function ListObject(arg1, arg2, arg3, arg4) {
  return window['go']['controller']['App']['ListObject'](arg1, arg2, arg3, arg4);
}

export function ShareObject(arg1, arg2, arg3) {
  return window['go']['controller']['App']['ShareObject'](arg1, arg2, arg3);
}

export function UploadObject(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['controller']['App']['UploadObject'](arg1, arg2, arg3, arg4, arg5);
}
