name: Auto Build Windows
on:
  push:
    tags:
      - 'v*'

jobs:
  build-job:
    runs-on: windows-latest
    permissions: write-all
    steps:
      - name: install node
        uses: actions/checkout@v4
        with:
          node-version: '18'

      - name: install golang
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: install dependency
        run: npm i -g pnpm

      - name: install wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: build
        run: wails build -ldflags='-s -w'

      - name: create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release_${{ github.ref_name }}.exe
          body_path: build/bin/nf_disk.exe