name: Auto Build Windows
on:
  push:
    branches: [ build ]
jobs:
  build-job:
    runs-on: windows-2022
    steps:
      - name: install node
        uses: actions/checkout@v4
        with:
          node-version: '18'

      - name: install golang
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: install dependency
        run: npm i -g pnpm

      - name: install wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: build
        run: wails build -ldflags='-s -w'