name: Auto Build Windows
on:
  push:
    tags:
      - 'v*'

jobs:
  build-job:
    runs-on: windows-latest
    permissions:
      id-token: write
      contents: write
      pull-requests: write
      repository-projects: write
    steps:
      - name: install node
        uses: actions/checkout@v4
        with:
          node-version: '18'

      - name: install golang
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: install dependency
        run: npm i -g pnpm

      - name: install wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: build
        run: wails build -ldflags='-s -w'

      - name: create release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ github.ref_name }}"
          title: "Release_${{ github.ref_name }}"
          files: build/bin/nf_disk.exe

#      - name: create release
#        id: create_release
#        uses: actions/create-release@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          tag_name: ${{ github.ref_name }}
#          release_name: Release_Windows_${{ github.ref_name }}
#          body: |
#            Release: ${{ github.ref_name }}
#            - v0.0.x auto release
#            - v0.0.1 simple functions done
#
#      - name: upload release asset
#        id: upload_release
#        uses: actions/upload-release-asset@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          upload_url: ${{ steps.create_release.outputs.upload_url }}
#          asset_path: build/bin/nf_disk.exe
#          asset_name: release_win_${{ github.ref_name }}.exe
#          # asset_content_type: application/zip